### ISSUE TITLE
Create relationships between the entities

### ISSUE THREAD

**Issue by ACSG-64** [ACSG-64/concord-real-time-workspaces#22]
According to the following diagram:

>       Diagram updated thanks to @collengura  and @tkshfj  suggestions.
> - The relationship between message and reply has been added.
> - Added timestamps as attributes for messages: `created_at `and `modified_at`, the latter in case the functionality to modify already sent messages is implemented.
> ![Concord DB design](https://user-images.githubusercontent.com/50815104/201696215-323b9f79-cabf-41e1-9561-5ca19c537506.png)
> 
> _Originally posted by @ACSG-64 in https://github.com/ACSG-64/concord-real-time-workspaces/discussions/4#discussioncomment-4129143_

    

Create the relationships between the entities/models.

**Comment by shno784** [comment]
This is the relationship I've done in Code:
![image](https://user-images.githubusercontent.com/82393008/204441672-971ddd06-3f9a-4b8e-9ced-10a349c7d522.png)
![image](https://user-images.githubusercontent.com/82393008/204441752-e9f80b40-6fb6-4d5b-8d38-3784fe9f6dc8.png)
![image](https://user-images.githubusercontent.com/82393008/204441774-1614ad9a-6ccc-4b88-922a-a4f3aea73b2c.png)
![image](https://user-images.githubusercontent.com/82393008/204441803-5e9ad89a-6604-4935-af60-187cdc2c2bc8.png)

I still think the messageid field in the message table should be changed to something like reply, Let me know what you think.

**Comment by ACSG-64** [comment]
Makes sense, something like `replyToMessageId` or  `replyToMsgId`

**Comment by ACSG-64** [comment]
You know, above each pair of relations you should add a comment saying the relation, something like:
```javascript
// User-Message
User.hasMany(Message);
Message.belongsTo(User);
```

**Comment by shno784** [comment]
![image](https://user-images.githubusercontent.com/82393008/204523684-0bcf70b2-7225-42bf-8df9-39ee3d34d713.png)
I had to remove `Message.belongsTo(Message)` below because it created another messageId column in the message table. 
![image](https://user-images.githubusercontent.com/82393008/204523957-9f154389-3968-4701-802b-4a920192ad4f.png)
Removing it fixed the problem
![image](https://user-images.githubusercontent.com/82393008/204524117-be55011e-52ba-4d46-8566-0a812b100535.png)

**Comment by shno784** [comment]
I have merged my branch into main and deleted, closing.
